# Generated by Django 4.2.5 on 2023-10-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("plat1", "GeoTracker"),
                            ("plat2", "GpsTracker"),
                            ("plat3", "Tacker"),
                        ],
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(blank=True, default=True)),
                ("bus_details", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperatorBuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceid", models.CharField(db_index=True)),
                ("tracker_approved", models.BooleanField(default=False)),
                ("bus_no", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator",
                        to="users.operator",
                    ),
                ),
            ],
            options={
                "db_table": "operator_buses",
            },
        ),
    ]
