# Generated by Django 4.2.5 on 2023-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dropdown_platform",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("other", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
