# Generated by Django 4.2.5 on 2023-10-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Operators",
        ),
    ]
