# Generated by Django 4.2.5 on 2023-10-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_user_operators"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Operators",
            new_name="Operator",
        ),
    ]
