# Generated by Django 4.2.5 on 2023-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_operator_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="is_traccar_approved",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
