# Generated by Django 4.2.5 on 2023-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_operators_operator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operator",
            old_name="dropdown_platform",
            new_name="platform",
        ),
        migrations.AlterField(
            model_name="operator",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="operator",
            name="password",
            field=models.CharField(default="def", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="operator",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
