# Generated by Django 4.2.5 on 2023-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_operator_is_traccar_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="bus_list",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
