# Generated by Django 4.2.5 on 2023-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_dropdown_platform_operator_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="platform",
            field=models.CharField(
                choices=[
                    ("plat1", "GeoTracker"),
                    ("plat2", "GpsTracker"),
                    ("plat3", "Tacker"),
                ],
                default=1,
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
