# Generated by Django 4.2.5 on 2023-10-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_operator_bus_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorbuses",
            name="tracker_approved",
        ),
    ]
