# Generated by Django 4.2.5 on 2023-10-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_operatorbuses_tracker_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_no", models.CharField(max_length=100)),
                ("uniqueId", models.BigIntegerField(blank=True, null=True)),
                ("is_traccar_approved", models.BooleanField(default=False)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.operator",
                    ),
                ),
            ],
        ),
    ]
