# Generated by Django 4.2.5 on 2023-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_buslist"),
    ]

    operations = [
        migrations.AddField(
            model_name="buslist",
            name="deviceId",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
