# Generated by Django 4.2.5 on 2023-10-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_buslist_deviceid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buslist",
            name="is_traccar_approved",
        ),
    ]
