# Generated by Django 4.2.5 on 2023-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_operator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
