# Generated by Django 4.2.5 on 2023-10-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_buslist_is_traccar_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="buslist",
            name="is_traccar_approved",
            field=models.BooleanField(default=False),
        ),
    ]
