# Generated by Django 4.2.5 on 2023-10-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_buslist_is_traccar_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buslist",
            name="is_traccar_approved",
        ),
    ]
