# Generated by Django 4.2.5 on 2023-10-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geotrack", "0005_rename_geodevdetails_geodevdetail"),
        ("users", "0009_operatorbusses"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OperatorBusses",
            new_name="OperatorBuses",
        ),
        migrations.AlterModelTable(
            name="operatorbuses",
            table="operator_buses",
        ),
    ]
