# Generated by Django 4.2.5 on 2023-10-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_operatorbusses_operatorbuses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorbuses",
            name="device_id",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
