# Generated by Django 4.2.5 on 2023-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_buslist_is_traccar_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="is_geotrak_approved",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
