# Generated by Django 4.2.5 on 2023-10-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_operatorbuses_device_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorbuses",
            name="device_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
