# Generated by Django 4.2.5 on 2023-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_operatorbuses_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorbuses",
            name="device_id",
        ),
        migrations.AddField(
            model_name="operatorbuses",
            name="deviceid",
            field=models.IntegerField(db_index=True, default=11, unique=True),
            preserve_default=False,
        ),
    ]
