# Generated by Django 4.2.5 on 2023-10-04 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_operatorbuses_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorbuses",
            name="deviceid",
            field=models.CharField(
                db_index=True,
                default=uuid.UUID("1c3aa5b1-bc70-47c1-ab17-8cde1600e2d8"),
                editable=False,
            ),
        ),
    ]
