# Generated by Django 4.2.5 on 2023-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_operatorbuses_deviceid"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="bus_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operator",
            name="tracker_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="operatorbuses",
            name="deviceid",
            field=models.CharField(db_index=True),
        ),
    ]
