# Generated by Django 4.2.5 on 2023-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_operator_bus_details_operator_tracker_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator",
            name="tracker_approved",
        ),
        migrations.AddField(
            model_name="operatorbuses",
            name="tracker_approved",
            field=models.BooleanField(default=False),
        ),
    ]
