# Generated by Django 4.2.5 on 2023-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_operator_is_approved_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
