# Generated by Django 4.2.5 on 2023-10-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_operator_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator",
            name="is_approved_tracker",
        ),
    ]
