# Generated by Django 4.2.5 on 2023-10-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0005_remove_operatorbuses_tracker_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoDevDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(blank=True, null=True)),
                ("deviceid", models.BigIntegerField(blank=True, null=True)),
                ("deviceTime", models.DateTimeField(blank=True, null=True)),
                ("fixtime", models.DateTimeField(blank=True, null=True)),
                (
                    "lattitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("speed", models.FloatField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "exceptionBM",
                    models.BigIntegerField(
                        blank=True, db_column="exceptionBM", null=True
                    ),
                ),
                ("direction", models.IntegerField(blank=True, null=True)),
                (
                    "haltedSince",
                    models.CharField(
                        blank=True, db_column="haltedSince", max_length=200, null=True
                    ),
                ),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                (
                    "distance",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "locStr",
                    models.CharField(
                        blank=True, db_column="locStr", max_length=200, null=True
                    ),
                ),
                (
                    "noDataSince",
                    models.CharField(
                        blank=True, db_column="noDataSince", max_length=200, null=True
                    ),
                ),
                (
                    "movingSince",
                    models.CharField(
                        blank=True, db_column="movingSince", max_length=200, null=True
                    ),
                ),
                (
                    "bmStr",
                    models.CharField(
                        blank=True, db_column="bmStr", max_length=200, null=True
                    ),
                ),
                ("is_sent_traccar", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geodevdetails",
                        to="users.operator",
                    ),
                ),
                (
                    "operatorbus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geodevdetails",
                        to="users.operatorbuses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ErrorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.operator",
                    ),
                ),
                (
                    "operatorbus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.operatorbuses",
                    ),
                ),
            ],
        ),
    ]
