# Generated by Django 4.2.5 on 2023-10-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_operator_password"),
        ("geotrack", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Error",
            new_name="ErrorDetail",
        ),
    ]
