# Generated by Django 4.2.5 on 2023-10-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geotrack", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geodevdetail",
            name="timestamp",
        ),
    ]
