# Generated by Django 4.2.5 on 2023-10-04 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_operator_password"),
        ("geotrack", "0002_rename_error_errordetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoDevDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(blank=True, max_length=200, null=True)),
                ("deviceid", models.BigIntegerField()),
                ("servertime", models.BigIntegerField(blank=True, null=True)),
                ("devicetime", models.BigIntegerField(blank=True, null=True)),
                ("fixtime", models.BigIntegerField()),
                ("valid", models.BooleanField(default=True)),
                ("altitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("speed", models.FloatField()),
                ("course", models.FloatField()),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("attributes", models.CharField(blank=True, max_length=200, null=True)),
                ("accuracy", models.FloatField()),
                ("network", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.operator",
                    ),
                ),
            ],
        ),
    ]
