# Generated by Django 4.2.5 on 2023-10-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_operatorbusses"),
        ("geotrack", "0003_geodevdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodevdetails",
            name="operator_bus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.operatorbusses",
            ),
        ),
        migrations.AlterField(
            model_name="geodevdetails",
            name="course",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geodevdetails",
            name="fixtime",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
