# Generated by Django 4.2.5 on 2023-10-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geotrack", "0004_alter_geodevdetail_bmstr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geodevdetail",
            name="operatorbus",
        ),
    ]
