# Generated by Django 4.2.5 on 2023-10-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geotrack", "0004_geodevdetail_operator_geodevdetail_operatorbus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="errordetail",
            name="busdeviceid",
        ),
    ]
