# Generated by Django 4.2.5 on 2023-10-10 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_operator_is_traccar_approved_and_more"),
        ("geotrack", "0005_remove_geodevdetail_operatorbus"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodevdetail",
            name="buslist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buslist",
                to="users.buslist",
            ),
        ),
    ]
