# Generated by Django 4.2.5 on 2023-10-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("geotrack", "0005_remove_errordetail_busdeviceid"),
    ]

    operations = [
        migrations.AddField(
            model_name="errordetail",
            name="operatorbus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.operatorbuses",
            ),
        ),
    ]
