# Generated by Django 4.2.5 on 2023-10-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_operatorbuses_device_id_and_more"),
        ("geotrack", "0006_alter_geodevdetail_accuracy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="geodevdetail",
            old_name="operator_bus",
            new_name="operatorbus",
        ),
        migrations.AddField(
            model_name="errordetail",
            name="busdeviceid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.operatorbuses",
            ),
        ),
    ]
