# Generated by Django 4.2.5 on 2023-10-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geotrack", "0006_geodevdetail_buslist"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodevdetail",
            name="uniqueid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
