# Generated by Django 4.2.5 on 2023-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geotrack", "0007_rename_operator_bus_geodevdetail_operatorbus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="geodevdetail",
            old_name="devicetime",
            new_name="deviceTime",
        ),
        migrations.RemoveField(
            model_name="geodevdetail",
            name="network",
        ),
        migrations.AlterField(
            model_name="geodevdetail",
            name="fixtime",
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="geodevdetail",
            name="protocol",
            field=models.CharField(default="TCP"),
        ),
    ]
