# Generated by Django 4.2.5 on 2023-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geotrack", "0008_rename_devicetime_geodevdetail_devicetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geodevdetail",
            name="accuracy",
            field=models.FloatField(default=0, null=True),
        ),
    ]
